# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lisimba's Blog
tagline:          ''
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://blog.lisimba.co.uk

author:
  name:           'Lisimba Gilkes'
  url:            https://lisimba.co.uk

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lisimba
